### ISSUE TITLE
Incorporate South Carolina Synthetic Unit Hydrograph Method (SC Synthetic UH)

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1344]
**South Carolina Synthetic Unit Hydrograph Method**

We are translating this spreadsheet into a storm runoff service for South Carolina:  [Spreadsheet for the SC Synthetic UH Method](https://doimspp.sharepoint.com/:x:/r/sites/SSPhaseII/Shared%20Documents/General/Planning/SC%20UH%20Method/SCDOT%20Spreadsheet_SC%20Synthetic%20UH%20Method_10%20June%202020.xlsm?d=w7adcdcb668f44f4e84347880f80b7844&csf=1&web=1&e=7pNbgk). The services are here (https://github.com/USGS-WiM/SC-RunoffModelingServices) and the StreamStats client work will be completed for this issue.

When you delineate a basin in South Carolina, you will click the "Open Storm Runoff Models" button in the sidebar (currently visible on this dev site: https://dev.streamstats.usgs.gov/sc-runoff/). Select the "SC Synthetic Unit Hydrograph" tab-- this is where the content for this issue will be added.

This is a large task that has been broken into smaller tasks. Feel free to break into even smaller issues.
- [x] Create basic user interface #1384 
- [x] Calculate parameters in user interface #1385
- [x] Compute output data #1386
- [x] Allow output tables to be downloaded as a CSV #1387
- [x] Allow report to be printable #1388
- [x] Add warning messages to report #1392 
- [x] Create user interface to enter Peak Rate Factor data #1421

Tips:
- Most of the work will be completed in SCStormRunoffController.ts and scstormrunoff.html
- The functionality for the "USGS SC Flood Hydrograph for Urban Watersheds" tab is complete and a good place to start looking for inspiration
- Make new branches based on the `SC-Runoff` branch for these issues. Pull requests should merge into the `SC-Runoff` branch. We will need to manually close issues after merge requests are completed, since we are not merging into the default branch.
