### ISSUE TITLE
v4.11.0 Release

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1438]
- [x] Update version numbers in the code
 - [x] Update CHANGELOG.md with all PR since last release
 - [x] Rebuild
 - [x] Pull request this branch -> dev (#1441)
 - [x] Pull request dev -> staging (#1442)
 - [x] Pull request staging -> master (#1443)
 - [x] Create release in Github with new version number https://github.com/USGS-WiM/StreamStats/releases/tag/v4.11.0
 
~- [ ] Push to dev and test site~ Found error, moving forward with release v4.11.1

This updated in this release
### Added
  - Flow Anywhere Method from StreamEst

  ### Changed
  - Channel Weighting services URL 
  - NWIS Page link from legacy real-time page to Next Generation Monitoring Location page
  - FlowAnywhereMapServices to StreamStatsMapServices because IowaStreamEst map services were moved from gis.wim.usgs.gov to gis.streamstats.usgs.gov
  - Flow Anywhere application shows published NWIS Drainage Area instead of GIS-calculated drainage area
  - Appconfig - SSstormwaterDelineation url in appconfig, Mystic configuration in appconfig, DRB configuration in appconfig (this was already on dev and never brought into gituhb)
