### ISSUE TITLE
Release v4.11.1

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1446]
- [x] Update version numbers in the code
 - [x] Update CHANGELOG.md with all PR since last release
 - [x] Rebuild
 - [x] Pull request this branch -> dev (#1445)
 - [x] Pull request dev -> staging (#1447)
 - [x] Pull request staging -> master (#1448)
 - [x] Create release in Github with new version number https://github.com/USGS-WiM/StreamStats/releases/tag/v4.11.1
 - [x] Deploy to Dev, Dev Mystic, and Test

# Changelog
### Added 

- Harper and Andrea to authors in package.json

### Fixed  

- Issue where state layers were not showing up
