### ISSUE TITLE
Create new Batch Processor interface

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1455]
Goal: Move the current Batch Processor (BP) (https://streamstatsags.cr.usgs.gov/ss_bp/) into the SteamStats client.

Rationale: The current Batch Processor lives on an external machine for which WIM doesn't have access and uses aging code and infrastructure. We would like to take advantage of modern frameworks and infrastructure and use our NSS services.

Create branches for each issue (ex. `AL-1456`) and make a Pull Request into the `batch-processor` branch when you are ready. Once the `batch-processor` branch is totally complete, we will merge it into `dev`. 

This is a large task that has been broken into smaller tasks:

- [x] Create a place for the new BP interface to live #1456 
- [x] Add "Select State/Region" dropdown #1457
- [x] Add "Compute Flow Statistics" checklist #1458
- [x] Add "Compute Basin Characteristics" checklist #1459
- [x] Add ID field, email address, shapefile uploader, and submit button #1460
- [x] Add user instructions #1461
- [x] Loaders #1615 and #1631
- [x] Create batch status tab #1594
- [x] Send inputs to service, POST request #1601 
- [x] Some BCs not appearing until Flow Statistic is selected #1646
- [x] Loader bug #1631
- [x] Descriptions for checkboxes? #1627
- [x] File upload button should be un-highlighted after a user uploads a file #1626 
- [x] Create batch queue management interface #1651
- [x] Add stream grids for download #1658

Feel free to add new issues as they come up! This list is a work in progress.
