### ISSUE TITLE
BP: Add "Compute Flow Statistics" checklist

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1458]
Part of #1455 

- [x] Create a checkbox that says "Compute Flow Statistics". When the checkbox is checked, the checklist (described below) should appear. When the checkbox is unchecked, the checklist should disappear.
- [x] Create a checklist that says "Select Flow Statistics:" 
- [x] When a Region/State is selected, make a service call to https://streamstats.usgs.gov/nssservices/Regions/AZ,NA/Scenarios (example is for Arizona; you include the "code" for the Region and then add ",NA" as well to include nation-wide Statistic Groups) to get a full list of all the Statistics Groups
- [x] Display the "statisticGroupName" of each Statistic Group in the checklist
- [x] Include a way (buttons?) to "Check all" and "Uncheck all" the flow statistics in the checklist

**Comment by laws-spatial** [comment]
- [ ] Populate array in controller with statistics
