### ISSUE TITLE
BP: Add "Compute Basin Characteristics" checklist

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1459]
Part of #1455 

- [x] Create a checkbox that says "Compute Basin Characteristics". When the checkbox is checked, the checklist (described below) should appear. When the checkbox is unchecked, the checklist should disappear.
- [x] If any Flow Statistics are checked, the "Compute Basin Characteristics" checkbox should be forcibly selected.
- [x] Create a checklist that says "Select Basin Characteristics:"
- [x] When a Region/State is selected, make a service call to https://streamstats.usgs.gov/streamstatsservices/parameters.json?rcode=AZ (example is for Arizona) to get a full list of the Basin Characteristics (aka "parameters")
- [x] Display both the "code" and "description" of each Basin Characteristic in the checklist; this may be best formatted as a table
- [x] When a Flow Statistic is checked, refer back to the service response used to retrieve Flow Statistics (https://streamstats.usgs.gov/nssservices/Regions/AZ,NA/Scenarios). Look at the specific Flow Statistic that was checked and look at the "parameters" listed. Forcibly check these Basin Characteristics in the checklist, since these Basin Characteristics must be computed in order to compute the desired Flow Statistics. 
- [x] The basin characteristic "DRNAEA" should always be checked (not allowed to be unchecked) if the "Compute Basin Characteristics" checkbox is checked
