### ISSUE TITLE
Stage vs. Discharge Plot

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1492]
**Background Information**: In [StreamStats](https://streamstats.usgs.gov/ss/), users can click on gages (represented as triangles on the map) to view more information about the gages, including a link to the "StreamStats Gage Page". We are in the process of updating the gage pop-up and StreamStats Gage Pages. When the user clicks the link to the StreamStats Gage Page, there will be 2 tabs-- one for Gage Information, and one for Gage Analysis Plots. On the Gage Analysis Plots tab, we will show a variety of plots, inspired by this page from the National Weather Service: https://www.weather.gov/source/aprfc/gageAnalysis.html?site=12340000. This issue will focus on adding a plot similar to the plot called "Stage vs. Discharge" on that page.

**Tasks**: 
- [x] Create a basic graph with "River Stage (ft)" data on the y-axis and "River Discharge (cfs)" data on the x-axis. Add a series of black squares with a black line called "USGS Rating Curve".
     - Stage and discharge data used to generate the rating curve can be retrieved from this web service: https://waterdata.usgs.gov/nwisweb/get_ratings?site_no=12340000&file_type=exsa. The first column is stage and the third column is discharge. You will want to make a GET request to that service and parse the data to get it into a form that will work with HighCharts.  
- [x] Add a series of dots called "USGS Measured". In the legend, this series should appear with a blue dot symbol.
     - Stage and discharge data from USGS measurements can be retrieved from this web service: https://waterdata.usgs.gov/nwis/measurements?site_no=12340000&agency_cd=USGS&format=rdb_expanded (it may be easier to view the data in [this format](https://waterdata.usgs.gov/nwis/measurements/?site_no=12340000&agency_cd=USGS) first to better understand it).
     - The most recent measurement should be a red dot
     - Measurements from the last year should be orange dots
     - Measurements that were made between 2 years and ago and 1 year ago should be this color: rgba(0,0,205,0.8)
     - Measurements older than 2 years ago should be this color: rgba(0,0,205,0.3)
- [x] Add a series of black dots called "Annual Peaks". Maggie has retrieved this data for #1424, so you should be able to recycle that data structure for this graph. 
- [x] User should be able to zoom into the graph
- [x] A legend with the name and symbology of the series should be visible
- Note: We do not need to add the "NWS Rating Curve" to the graph.

**Tips**:
- The graphing library we will be using is [HighCharts](https://www.highcharts.com/)
- Maggie is has worked on a gage analysis plot (#1424) that now appears in the `gageplots` branch. It may be helpful to look at her work in the `gageplots` branch in the gageplot.html and GagePlotController.ts files. 
- If you go to https://www.weather.gov/source/aprfc/gageAnalysis.html?site=12340000, right click "View Source", you will be able to view the source code for that webpage along with all of its plots. The developer who wrote this page said we could look and use the code. The plot we want to recreate has an id of "ratinggraph". 
     - Line 5118 setupGraphRating function: sets up the HighChart plot 
     - Line 1587 addUSGSrating function: retrieves the data from the USGS National Water Information System (NWIS), gets it into the correct form for HighCharts, and adds data to the plot
     - You may see calls to https://www.chenabasin.org/. It seems that this service translates the NWIS service calls into nicely formatted results. However, we don't have access to this service and can't guarantee it will remain online, so we will need to USGS services instead. 
- You will be working off of the branch called `gageplots`, which has this updated gage popup and StreamStats Gage Page with 2 tabs. Your work will primarily go in [this section of gagepage.html](https://github.com/USGS-WiM/StreamStats/blob/gageplots/src/Views/gagepage.html#L198L204) and [GagePageController.ts](https://github.com/USGS-WiM/StreamStats/blob/gageplots/src/Controllers/GagePageController.ts). 
- Pull requests should merge into the `gageplots` branch. We will need to manually close issues after merge requests are completed, since we are not merging into the default branch

Next issue: #1555

**Comment by USGSPMM3** [comment]
- This might be my monitor, but the plot does not completely fit in my scrollable area. I have to scroll up and down continuously to see all of the information. See image below.
- A user should be able to hover over the flood quantile lines and see the values. 
- When  zoom to a specific time period, the y-scale resets and doesn't allow me to see how far below the flood quantile values I am. 
- I like the NWS plot default which shows the day of year of peaks with the flow duration shading and a dark blue line with current streamflow. The timing of peaks plotted on a single year is informative for flood-frequency analyses. See figure below.
- If we do the above (plot ALL peaks on day of year regardless of which year is selected, I think there should be a toggle to plot peaks a) on actual date of occurrence, or b) plot all peaks on day of year. The quick zoom button allows the user to quickly zoom to the current data.
- When I click on the date to change it, the entry box is further up and left then I would like. When entering dates, a tab should move the user to the next entry area. If the box was bigger it would be easier to see the calendar for selecting dates if a user didn't want to enter them manually. 
- If there is missing data, don't draw a line across the missing period. Stop the line and restart. 
- In the zoom options for 1m, 3m, etc, I was expecting to have those zoom to the LAST 1m or 3m of data. What it appears to do is set the x-axis zoom to that scale regardless of where you are in the full time period. 
- Add option to add the NWS forecast data (maybe leave on for default plot?)

![image](https://user-images.githubusercontent.com/16928289/217103762-2fda9a45-c149-4892-8fc0-ea58b42c6d02.png)
![image](https://user-images.githubusercontent.com/16928289/217104690-983274d0-a5e1-474d-8de1-f4b4d81b287e.png)

**Comment by amedenblik** [comment]
@USGSPMM3 This feedback concerns a different plot (not the Stage vs. Discharge plot, which is this issue) so I have created a new issue for your notes: #1537

**Comment by USGSPMM3** [comment]
@amedenblik Oh no! I didn't even look at the title of this one, just grabbed the link in the note from last week. Sorry!
