### ISSUE TITLE
Daily Value Raster Plot

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1499]
**Background Information**: In [StreamStats](https://streamstats.usgs.gov/ss/), users can click on gages (represented as triangles on the map) to view more information about the gages, including a link to the "StreamStats Gage Page". When the user clicks the link to the StreamStats Gage Page, there will be 2 tabs-- one for Gage Information, and one for Gage Analysis Plots. On the Gage Analysis Plots tab, we will show a variety of plots, inspired by this page from the National Weather Service: https://www.weather.gov/source/aprfc/gageAnalysis.html?site=06893000. This issue will focus on adding a plot similar to the plot called "Daily Data" on that page. This plot is really two plots that are displayed next to one another. One is a plot of the daily flow value and the other is a plot of the annual average daily flow values. 

**Tasks**:  
- [x] Create daily plot.
    - [x] Use the `getDailyFlow` function to get all the daily data needed for this plot. Since both the Annual Flow Plot & this new Daily Data plot are using this same function, we should try to only call it once. This will limit the amount of service calls we make, thus making the application run more efficiently then if we call it separately for each plot. 
    - [x] Create a heatmap. Months should be on the x-axis, starting with Oct 1 (1st day of the water year) and ending with September 30th (last day of the water year), and water years on the y-axis. The values in each cell are based on the daily flow value for that date. It looks like the legend is on a logarithmic scale (see line 5383 of the national weather service code.)
    - [x] Add option to hover over cell and see a tool tip with the date, water year, and daily value.

---------------Feel free to break items below this line into new issue---------------

- [x] Create annual average plot.
    - [x] Create an annual heatmap. For this plot there should be just one column on the x axis, labeled Annual, and the y-axis should be in water years like the daily plot. To get the annual value, you need to take the average daily value of the entire water year. This will be the value used for each cell.
    - [x] Add option to hover over cell and see a tool tip with the water year and average daily value.
- [x] Display plots next to each other. In the national weather service code, it looks like the daily and annual are two different plots, see line 155 and 156, that are just displayed next to each other.  

**Tips**:
- If you go to https://www.weather.gov/source/aprfc/gageAnalysis.html?site=06893000, right click "View Source", you will be able to view the source code for that webpage along with all of its plots. The developer who wrote this page said we could look and use the code. The plot we want to recreate is called `heatchartobj` and `annualheatchartobj`.
    - They use heatmaps to create this plot, https://www.highcharts.com/demo/heatmap 
    - In function `setupGraphHeatQ`, you can see how the daily plot is formatted.  
    - In function `setupAnnualHeatQ`, you can see how the annual plot is formatted. 
- The graphing library we will be using is [HighCharts](https://www.highcharts.com/). 
- You will be working off of the branch called `gageplots`, primarily in the gagepage.html and GagePageController.ts. Pull requests should merge into the `gageplots` branch. We will need to manually close issues after merge requests are completed, since we are not merging into the default branch

**Comment by amedenblik** [comment]
Closed with #1558
