### ISSUE TITLE
Create MN Sediment workflow

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1544]
This is the parent issue for the MN Sediment workflow issues.

- [x] 1. Add configuration button to sidebar #1915
- [x] 2. Create modal #1916
- [x] 3. Add date range to modal #1917
- [ ] 4. Add streamflow selection to modal #1919
- [ ] 5. Select requisite BCs #1920
- [ ] 6. Add blank report section #1922
- [ ] 7. Add model inputs to report #1926
- [ ] 8. Add citation and warnings to report #1928
- [ ] 9. Make requests to SedStats #1923
- [ ] 10. Add graph to report #1929
- [ ] 11. Add output data table to report #1930
- [ ] 12. Allow option to download this section as a CSV #1931
- [ ] 13. Add MN DRN streamflow selection #1932
- [ ] 14. Add FDCTM streamflow selection #1933
- [ ] 15. Add streamflow upload option #1935

**User Story**
1.	User delineates a basin in MN
2.	User clicks "Continue" in the left sidebar
3.	A button will appear at the bottom of the "Select Scenarios" section: "Configure Sediment Machine Learning Methods"
4.	When the user clicks the "Configure Sediment Machine Learning Methods" button, a modal will appear
5.	In the modal, the user will configure:
     - Date range
     - Streamflow: * note: streamflow may be daily, hourly, or 15-minute
         - Select a USGS gage and use that gage's streamflow
             - Select from the map 
             - Query nearest gages
         - Select an MN DNR gage and use that gage's streamflow
             - Select from the map? (depends on API options)
             - Select one from a list  
         - Estimate streamflow via FDCTM
         - Upload streamflow via a CSV (user will be provided with a template)
      - Note: the modal should also have instructions and warnings about the model 
7.	If the user has configured the "Configure Sediment Machine Learning Methods", any requisite Basin Characteristics will be checked by default (some basin characteristics that are necessary for the model may already exist in SS, and other will need to be retrieved via an API)
8.	User continues with the workflow and opens the Report
9.	The Report will contain the following in the "Sediment Machine Learning Methods" section:
     - Graph of suspended sediment and bedload on different y axes
     - Expandable table with date, (estimated) streamflow, estimated suspended sediment, and estimated bedload (we may consider other time scales --hourly, 15-minute, daily-- depending on timescale of input data)
     - Model inputs:
         - Information about reference gage, if applicable
         - Model parameters: date range, basin characteristics
     - Citation
     - Option to download this section as its own CSV
     - Warnings about values that are out of the model range
     - General warnings about the model 

**Other tasks**
* Add map layer for sediment regions https://github.com/USGS-WiM/StreamStats/issues/1670
* Add map layer river size class https://github.com/USGS-WiM/StreamStats/issues/1671
* Include the map layers on the report

**Comment by amedenblik** [comment]
Mockups from @chaqazarad 

![image](https://user-images.githubusercontent.com/40237491/219712750-94cddad9-892d-46d6-b477-2cffa0c48700.png)
![image (1)](https://user-images.githubusercontent.com/40237491/219712779-2373192e-eea2-4de6-8d8e-fafb49767649.png)
![image (2)](https://user-images.githubusercontent.com/40237491/219712783-2754127b-874a-4429-985c-a30d7020d04c.png)
![image (3)](https://user-images.githubusercontent.com/40237491/219712801-c99fdfb6-004e-4e44-97dd-5191a49841b9.png)
![image (4)](https://user-images.githubusercontent.com/40237491/219712819-a60c536e-a10d-44af-a838-f46e721040a2.png)
![image (5)](https://user-images.githubusercontent.com/40237491/219712820-050398c6-9386-4ade-8340-b9c8d1128164.png)
![image (6)](https://user-images.githubusercontent.com/40237491/219712830-aa48ac8a-f6b6-485e-b39b-7c2b14abb3f6.png)
![image (7)](https://user-images.githubusercontent.com/40237491/219712851-0975c838-51b5-4a04-ad18-f80aa9791623.png)

All mockups here: [mockups.zip](https://github.com/USGS-WiM/StreamStats/files/10768942/mockups.zip)
