### ISSUE TITLE
Release 4.16.0

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1635]
After #1634

- [x] Update version numbers in the code
- [x] Update CHANGELOG.md with all PR since last release
- [x] Rebuild
- [x] Push to dev #1637
- [x] Push to test #1638
- [x] Push to master #1639
- [x] Create release in Github with new version number https://github.com/USGS-WiM/StreamStats/releases/tag/v4.16.0
- [x] Push to dev and test site
- [x] Push to prod #1629
