### ISSUE TITLE
Update BP Service URLs ( after deploy )

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1686]
When we have deployed the BP services to a dev and production environment we need to update the BP URLs.

-  [x] Update in the appconfig. 
    - [x] Dev & Test- [Line 21](https://github.com/USGS-WiM/StreamStats/blob/batch-processor/src/appConfig.js#L21) should point to the devURL. We are disabling the BP on test #1763 so line 21 can always point to the URL.
    - [x] Production - we will need to add a new line `if (window.location.host === 'streamstats.usgs.gov')` to point to the production URL.
    - [x] Update Stream Grids https://github.com/USGS-WiM/StreamStats/issues/1768
- [ ] Update the manage queue URLs. 
    - [x] Dev- [update line 901](https://github.com/USGS-WiM/StreamStats/pull/1687/files#diff-f4968787b9d4ca9c35f7a9cec7cd0785448148fcfbe838b2e2e658a96461b006R901)
    - [x] Production - [update line 897](https://github.com/USGS-WiM/StreamStats/pull/1687/files#diff-f4968787b9d4ca9c35f7a9cec7cd0785448148fcfbe838b2e2e658a96461b006R897)
    - [ ] Check to make sure the pause, deletes, order queue, are hitting the correct service urls for the queue selected. It should work but I wasn't able to 100% check with #1677

**Comment by harper-wavra** [comment]
Related issue #1763
