### ISSUE TITLE
Release 4.19.0

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1848]
- [x] Update version numbers in the code
- [x] Update CHANGELOG.md with all PR since last release
- [x] Rebuild 
- [x] Push to dev #1856
- [x] Push to staging #1858
- [x] Push to master #1859
- [x] Create release in GitHub with new version number https://github.com/USGS-WiM/StreamStats/releases/tag/v4.19.0
- [x] Deploy: 
     - [x] dev
     - [x] test
     - [x] manage queue site

### Added

- Note about Batch Processor output projection
- appConfig files for dev and test machines
- Instructions about shapefile structure to Batch Processor Submit Batch tab
- Checkbox option to ignore exclusion polygons on non-Production servers
- Allow option to run Dev Batch Processor points that are in exclusion polygons
- Error message in Batch Processor is Batch Processor services aren't working
- "Start Next Batch" button to Batch Processor Manage Queue tab
- Ability to refresh batches in Batch Processor Manage Queue tab
- Mystic River Basin region 

### Changed

- Batch Processor streamgrids retrieved from different endpoints
- Batch Processor times displayed in local time instead of UTC
- Use SS Pourpoint ssExcludePolygon service instead of directly using state map services
- Batch Processor Download Stream Grids tab files now also include Exclude Polys

### Fixed

- Latitude and Longitude columns swapped in the Elevation profile CSV export
- Email address required for Batch Processor Batch Status tab
