### ISSUE TITLE
Finish line delineation

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1852]
See #1169 and #1828 

Remaining tasks: (can create new issue(s))

**Essential**

- [x] I can't get basins to load when there are more than 2 intersection points. See [comment](https://github.com/USGS-WiM/StreamStats/issues/1852#issuecomment-1861633045).
- [x] If clicking second point too fast the line doesn't stop after two clicks #1903 
- [x] Need to deal with "additional features" (like longest flow path) #1901
    -  For longest flow path, use the longest of the individual basins.
- [x] Include an upper limit on the length of the line. ~~This could be by distance, in which case we could reuse code from the measure tool (client-side), or by the number of intersection points (service change). May need Pete's input on this.~~ https://github.com/USGS-WiM/StreamStats/pull/1902
    - [x] 10 intersections and 
    - [x] 2.5 miles 
- [x] Delete console.logs #1903 
- [ ] Improve Google analytics -- not sure if this is needed or what could be added?
     - Added Delineation Line to the [StreamStats Google Analytics Event Tracker](https://doimspp.sharepoint.com/:x:/r/sites/GS-UMidWIM/Shared%20Documents/Projects/Streamstats%20Ecosystem/StreamStats%20Google%20Analytics%20Event%20Tracker.xlsx?d=w759edfb901a648cb807e1f65561fde80&csf=1&web=1&e=h7ZP5I)
- Check that all aspects of the Report and the report downloadables (CSV, shapefile, etc.) still work #1902 
    - [x] Check download basin options [image](https://github.com/USGS-WiM/StreamStats/assets/59063181/284f55bd-b171-46ec-af54-4374597887b6) 
    - [x] Check report download. This is just spinning currently. 
- [x] Make sure Regulation feature works
- [x] Make sure Runoff Models feature still works with point delineation #1901 
- [x] Disable Runoff Models for line delineation #1901
- [x] Do testing to ensure all normal (point delineation) workflows still work
- [x] Disable NHD stream query for line delineation #1901
- [x] If you do a delineation, and then click Clear Basin, only one of the Delineate buttons appear (either Delineate or Delineate by Line, whichever was used). Then if you click that Delineate button, the other Delineate button does appear again and is disabled.  https://github.com/USGS-WiM/StreamStats/pull/1902
- [x] If you draw a line in a hard exclude poly, it fails. Then you can try again and draw another line, but the old line still appears. The old line should disappear once a new line is drawn. https://github.com/USGS-WiM/StreamStats/pull/1902
- [x] Make sure sub-basins still appear on the Legend (turned off by default) & get cleared when clearing a basin. https://github.com/USGS-WiM/StreamStats/pull/1902

**Would be nice**

- [x] If you click "Delineate by Line" and immediately click "Delineate by Line", then click "Delineate", the line drawing interface is still active. Point delineation does still work though. Moved to #1883 
- [x] If you click Clear Basin, the drawn line and Basin Clicked Points still appear on the map. (The subbasins/etc. no longer show up after https://github.com/USGS-WiM/wim_angular/pull/113) https://github.com/USGS-WiM/StreamStats/pull/1902
- [x] After the line intersection occurs but before delineation finishes, the last intersection point marker has a popup. We should turn off the popups because it's strange to just have one popup appear.  Done in #1885 
- [x] The spin icons in both the "Delineation" and "Delineate by Line" buttons spin while the delineation is happening. Might look nice if only the relevant one is spinning. Moved to #1883 
- [x] Sometimes the cursor is still spinning after delineation, etc. is finished. Not sure if the browser is just slow/loading or if we need to / can change something in the code to fix this. Done in #1885

**Comment by harper-wavra** [comment]
[4 points](https://github.com/USGS-WiM/StreamStats/assets/59063181/0dc8e0e7-0416-42d2-96f2-cc2c87998bc7)
I was able to get this delineation with 4 intersection points to load & compute peak flows. I think Ander's updates to the line intersection endpoint helped. Will check off the top item for now, but if we are still seeing issues can look into more.

**Comment by harper-wavra** [comment]
@USGSPMM3 I think we are at the point in line delineation where we can add an upper line length. Do you want to go by the number of intersection points or the distance between the two points? & what should those limits be?
