### ISSUE TITLE
Release v4.19.1

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1864]
- [x] Update version numbers in the code
- [x] Update CHANGELOG.md with all PR since last release
- [x] Rebuild 
- [x] Push to dev #1865
- [x] Push to staging #1866
- [x] Push to master #1867
- [x] Create release in GitHub with new version number https://github.com/USGS-WiM/StreamStats/releases/tag/v4.19.1
- [x] Deploy: 
     - [x] dev
     - [x] test
     - [x] manage queue site
     - [x] Prod

### Fixed

- Added back .zip files to stream grid download URLs
