### ISSUE TITLE
MN Sediment - Create blank modal

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1916]
Parent issue is #1544 

## User Story

(continued from previous issue)

1. In the "SELECT SCENARIOS" section of the sidebar, below the "Basin Characteristics" section, user clicks the "Configure Sediment Machine Learning Method" button
2. A new modal appears 

## Tasks

- [x] Create files for a new modal: Views/sedimentview.html, Controllers/SedimentController.ts
  - Hint: Use the Flow Anywhere Method (Views/flowanywhere.html and Controllers/FlowAnywhereController.ts) and FDCTM (Views/extensionview.html and Controllers/ExtensionModalController.ts) as examples
- [x] Add the new Controller to the index.html file
- [x] Edit Services/ModalService.ts to include the new modal
- [x] Ensure the modal opens when you click the "Configure Sediment Machine Learning Method" button
- [x] Modal title should be "Sediment Machine Learning Method"
- [x] Modal description should be "The sediment machine learning method estimates suspended-sediment concentrations and bedload for non-sampled streams in Minnesota."
- The rest of the modal can be blank for now.

**Comment by amedenblik** [comment]
Closed with #1938
