### ISSUE TITLE
MN Sediment - Add date range selector to modal

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1917]
Parent issue is #1544

## User Story

(continued from previous issue)

1. User is looking at the "Sediment Machine Learning Method" modal
2. Users selects a date range

## Tasks

- [x] Create a section of the modal that is titled "Select/Enter a Date Range (Required)"
- [x] At the end of a title, include a question mark icon that shows this text when the user hovers: "Date range is limited to 2006 and later due to model limitations."
- [x] Add a date range selector.
- [x] Prevent users from selecting dates before 2006-01-01
- [x] Include "Cancel" and "Ok" buttons at the bottom of the modal
- [x] The "Cancel" button should close the modal
- [x] The "Ok" button should be disabled unless all required elements are completed. So far, the only required element will be the date range selector.
- [x] When the user clicks the "Ok" button, the modal should close and a success toast should appear: "Sediment Machine Learning Method was successfully configured" / "Please continue"
- Hint: Use the "Flow Anywhere Model" modal and toast as an example

**Comment by amedenblik** [comment]
Closed with #1940
