### ISSUE TITLE
MN Sediment - Add streamflow selection to modal

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1919]
Parent issue is #1544

## User Story
(continued from previous issue)

1. User is looking at the "Sediment Machine Learning Method" modal
2. User selects a USGS gage to use that gage's streamflow for the model

## Tasks

- [x] Create a section of the modal that is titled "Select a USGS Gage for Streamflow (Required)"
- [ ] Replicate the gage selection functionality that is in the FDCTM modal, except remove the "Best Correlated" button:
![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/3634a263-46de-4a95-ac6c-07b38e5b1425)
- [x] Add a button to the left of those that says "Enter Station Number". When clicked, show this interface:
![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/3fe22f4e-1315-4601-a9c3-5009059e3454)
     - (This is the same "Enter Station Number" interface as in the FDCTM modal, but I'd like to change it to be hidden unless the button is clicked to make it a little more consistent/sleek)
- [ ] The "Ok" button should be disabled until a gage is selected
- Note: we will add other methods of streamflow later, but for now we will start with this method
