### ISSUE TITLE
MN Sediment - Select requisite BCs

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1920]
Parent issue is #1544

## User Story

(continued from previous issue)

1. User is looking at the "Sediment Machine Learning Method" modal
2. User has configured required elements and clicks the "Ok" button

## Tasks

- [x] In the "SELECT SCENARIOS" section of the sidebar, in the "Basin Characteristics" section, the following Basin Characteristics should be checked:
     - DRNAREA
     - SSURGOC
- [x] The user should not be able to de-select these basin characteristics
- [x] If the user tries to de-select these basin characteristics, a warning toast should appear like this:
![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/98c074dc-eec3-4270-95b4-40c444c4d741)
- [x] When the user clicks the "Continue" button, all the checked basin characteristics are computed
     - Note: the service that computes basin characteristics can be inconsistent; it is not unusual for the basin characteristics to not compute on the first try
